services:
  frontend:
    build:
      context: ./example-frontend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  backend:
    build:
      context: ./example-backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
