name: Release Node.js app

on:
  push:
    branches:
      - main
    paths:
        - 'devops-with-docker/part3/express-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: devops-with-docker/part3/express-app

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: devops-with-docker/part3/express-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest
